language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pycodestyle"
  - "pip install pylint"
  - "pip install mypy"

script:
  - "coverage run --source=mnemonicode setup.py test"
  - "pycodestyle mnemonicode setup.py"
  - "pyflakes mnemonicode setup.py"
  - "pylint -E mnemonicode setup.py"
  - "mypy mnemonicode"

after_success:
  - "coveralls"

deploy:
  provider: pypi
  user: "bwhmather-travis"
  password:
    secure: "obcTLRBOVAnEGyMpOnv+/AZriOPha8WPl6ftgZmJNS++Jo/9N37zIH1xODjstWj+784NzPIoUgKQYfviFCAcB62wxBQRpd3Rqu7R6XhM5oCh/pkKqqRHXyNeB+8lhQ3WsU+2Tp/hFgSPM6OpBIS5sc1UvwqCLXxDDIBksX5e12M="
  on:
    branch: "master"
    condition: "\"${TRAVIS_PYTHON_VERSION}\" = '3.8'"
