language: python
sudo: false

matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=isort
    - python: "3.8"
      env: TOXENV=pycodestyle
    - python: "3.8"
      env: TOXENV=pyflakes
    - python: "3.8"
      env: TOXENV=pylint
    - python: "3.8"
      env: TOXENV=mypy
    - python: "3.8"
      install:
        - "pip install -e ."
        - "pip install coveralls"
      script:
        - "coverage run --source=mnemonicode setup.py test"
        - "coveralls"

install:
  - "pip install tox"

script:
  - "tox"

deploy:
  provider: pypi
  user: "bwhmather-travis"
  password:
    secure: "obcTLRBOVAnEGyMpOnv+/AZriOPha8WPl6ftgZmJNS++Jo/9N37zIH1xODjstWj+784NzPIoUgKQYfviFCAcB62wxBQRpd3Rqu7R6XhM5oCh/pkKqqRHXyNeB+8lhQ3WsU+2Tp/hFgSPM6OpBIS5sc1UvwqCLXxDDIBksX5e12M="
  on:
    branch: "master"
    condition: "\"${TRAVIS_PYTHON_VERSION}\" = '3.8'"
